#!/bin/bash
# Update_Game_Library_v1.1.sh
# Companion updater for MiSTer Game Library Audit v1.1.
# Safely previews/applies reviewed game + save rename proposals and can roll back the last run.

ROOT="/media/fat"
GAMES="$ROOT/games"
SAVES="$ROOT/saves"
AUDIT="$ROOT/GameLibraryAudit"
GAME_CSV="$AUDIT/proposed_renames.csv"
SAVE_CSV="$AUDIT/proposed_save_renames.csv"
HISTORY="$AUDIT/RenameHistory"
PLAN="$AUDIT/apply_preview.tsv"
SKIPS="$AUDIT/apply_skipped.tsv"

mkdir -p "$HISTORY" || exit 1

# Parse one RFC4180-ish CSV row generated by our auditor into CSV_FIELDS[].
parse_csv() {
  local s="$1" c field="" quoted=0 i
  CSV_FIELDS=()
  for ((i=0; i<${#s}; i++)); do
    c="${s:i:1}"
    if (( quoted )); then
      if [[ "$c" == '"' ]]; then
        if [[ "${s:i+1:1}" == '"' ]]; then field+='"'; ((i++)); else quoted=0; fi
      else field+="$c"; fi
    else
      case "$c" in
        '"') quoted=1 ;;
        ',') CSV_FIELDS+=("$field"); field="" ;;
        *) field+="$c" ;;
      esac
    fi
  done
  CSV_FIELDS+=("$field")
}

safe_under() { case "$1" in "$2"/*) return 0;; *) return 1;; esac; }
unsafe_name() { [[ -z "$1" || "$1" == */* || "$1" == "." || "$1" == ".." ]]; }

build_plan() {
  : > "$PLAN"; : > "$SKIPS"
  printf 'type\told_path\tnew_path\n' >> "$PLAN"
  printf 'type\tpath\treason\n' >> "$SKIPS"
  declare -A TARGETS
  local line old proposed new dir ext type

  if [[ ! -f "$GAME_CSV" ]]; then echo "Missing $GAME_CSV"; return 1; fi
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" == '"system"'* ]] && continue
    parse_csv "$line"
    old="${CSV_FIELDS[1]}"; proposed="${CSV_FIELDS[2]}"; type="GAME"
    safe_under "$old" "$GAMES" || { printf '%s\t%s\t%s\n' "$type" "$old" "outside games root" >> "$SKIPS"; continue; }
    unsafe_name "$proposed" && { printf '%s\t%s\t%s\n' "$type" "$old" "unsafe proposed filename" >> "$SKIPS"; continue; }
    ext="${old##*.}"; ext="${ext,,}"
    [[ "$ext" == "cue" ]] && { printf '%s\t%s\t%s\n' "$type" "$old" "CUE/BIN set rename disabled" >> "$SKIPS"; continue; }
    [[ -e "$old" ]] || { printf '%s\t%s\t%s\n' "$type" "$old" "source missing" >> "$SKIPS"; continue; }
    dir="${old%/*}"; new="$dir/$proposed"
    [[ "$old" == "$new" ]] && continue
    if [[ -e "$new" ]]; then printf '%s\t%s\t%s\n' "$type" "$old" "target already exists: $new" >> "$SKIPS"; continue; fi
    if [[ -n "${TARGETS[$new]}" ]]; then printf '%s\t%s\t%s\n' "$type" "$old" "duplicate proposed target: $new" >> "$SKIPS"; continue; fi
    TARGETS["$new"]="$old"
    printf '%s\t%s\t%s\n' "$type" "$old" "$new" >> "$PLAN"
  done < "$GAME_CSV"

  if [[ -f "$SAVE_CSV" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" == '"system"'* ]] && continue
      parse_csv "$line"
      old="${CSV_FIELDS[2]}"; proposed="${CSV_FIELDS[3]}"; type="SAVE"
      safe_under "$old" "$SAVES" || { printf '%s\t%s\t%s\n' "$type" "$old" "outside saves root" >> "$SKIPS"; continue; }
      unsafe_name "$proposed" && { printf '%s\t%s\t%s\n' "$type" "$old" "unsafe proposed filename" >> "$SKIPS"; continue; }
      [[ -e "$old" ]] || { printf '%s\t%s\t%s\n' "$type" "$old" "source missing" >> "$SKIPS"; continue; }
      dir="${old%/*}"; new="$dir/$proposed"
      [[ "$old" == "$new" ]] && continue
      if [[ -e "$new" ]]; then printf '%s\t%s\t%s\n' "$type" "$old" "target already exists: $new" >> "$SKIPS"; continue; fi
      if [[ -n "${TARGETS[$new]}" ]]; then printf '%s\t%s\t%s\n' "$type" "$old" "duplicate proposed target: $new" >> "$SKIPS"; continue; fi
      TARGETS["$new"]="$old"
      printf '%s\t%s\t%s\n' "$type" "$old" "$new" >> "$PLAN"
    done < "$SAVE_CSV"
  fi
}

preview() {
  build_plan || return 1
  local n s
  n=$(( $(wc -l < "$PLAN") - 1 )); s=$(( $(wc -l < "$SKIPS") - 1 ))
  echo; echo "Safe rename candidates: $n"; echo "Skipped/review items: $s"
  echo "Preview: $PLAN"; echo "Skipped: $SKIPS"; echo
  sed -n '1,21p' "$PLAN"
  (( n > 20 )) && echo "... see $PLAN for the full preview."
}

apply_plan() {
  preview || return 1
  local n stamp manifest type old new ok=0 fail=0
  n=$(( $(wc -l < "$PLAN") - 1 ))
  (( n > 0 )) || { echo "Nothing safe to rename."; return 0; }
  echo; echo "This will rename $n files. No ROM/save contents are modified."
  echo "Type APPLY exactly to continue:"
  read -r confirm
  [[ "$confirm" == "APPLY" ]] || { echo "Cancelled."; return 0; }
  stamp=$(date +%Y%m%d-%H%M%S)
  manifest="$HISTORY/rename-$stamp.tsv"
  printf 'type\told_path\tnew_path\tresult\n' > "$manifest"
  tail -n +2 "$PLAN" | while IFS=$'\t' read -r type old new; do
    if [[ -e "$old" && ! -e "$new" ]]; then
      if mv -- "$old" "$new"; then printf '%s\t%s\t%s\tOK\n' "$type" "$old" "$new" >> "$manifest"; else printf '%s\t%s\t%s\tFAILED\n' "$type" "$old" "$new" >> "$manifest"; fi
    else printf '%s\t%s\t%s\tSKIPPED_AT_APPLY\n' "$type" "$old" "$new" >> "$manifest"; fi
  done
  cp "$manifest" "$HISTORY/last_manifest.tsv"
  echo "Finished. Rollback manifest: $manifest"
  echo "Run the auditor again before making another cleanup pass."
}

rollback() {
  local manifest="$HISTORY/last_manifest.tsv" type old new result count=0
  [[ -f "$manifest" ]] || { echo "No last rollback manifest found."; return 1; }
  echo "Rollback will restore successful renames from:"; echo "$manifest"
  echo "Type ROLLBACK exactly to continue:"
  read -r confirm
  [[ "$confirm" == "ROLLBACK" ]] || { echo "Cancelled."; return 0; }
  # Reverse order to reduce dependency/collision risk.
  tail -n +2 "$manifest" | tac | while IFS=$'\t' read -r type old new result; do
    [[ "$result" == "OK" ]] || continue
    if [[ -e "$new" && ! -e "$old" ]]; then mv -- "$new" "$old" || echo "FAILED: $new"; else echo "SKIP: cannot safely restore $old"; fi
  done
  echo "Rollback pass finished. Re-run the auditor to verify the library."
}

echo "MiSTer Game Library Updater v1.1"
echo "================================="
echo "1) Preview safe renames"
echo "2) Apply safe renames"
echo "3) Roll back last applied cleanup"
echo "4) Exit"
read -r choice
case "$choice" in
  1) preview ;;
  2) apply_plan ;;
  3) rollback ;;
  *) exit 0 ;;
esac
