from pathlib import Path
p=Path('Export_Game_Library.sh'); s=p.read_text()
# Reuse discovery-time metadata for hashing and normalized-header checks.
s=s.replace('normalized_dat_hash() {\n  local p="$1" ext="${2,,}" raw="${3,,}" size alt=""\n  [ -n "${DAT_NAME_BY_SHA[$raw]+x}" ] && { printf \'%s\' "$raw"; return; }\n  size=$(stat -c \'%s\' "$p" 2>/dev/null)\n  [ -z "$size" ] && size=$(stat -f \'%z\' "$p" 2>/dev/null)', 'normalized_dat_hash() {\n  local p="$1" ext="${2,,}" raw="${3,,}" size="${4:-}" alt=""\n  [ -n "${DAT_NAME_BY_SHA[$raw]+x}" ] && { printf \'%s\' "$raw"; return; }\n  if [ -z "$size" ]; then size=$(stat -c \'%s\' "$p" 2>/dev/null); [ -z "$size" ] && size=$(stat -f \'%z\' "$p" 2>/dev/null); fi')
# One shell write per CSV row.
needle='csv_escape() { local s="$1"; s="${s//\\\"/\\\"\\\"}"; printf \'"%s"\' "$s"; }\n'
insert=needle+'csv_row() { local dest="$1" out="" v; shift; for v in "$@"; do v="${v//\\\"/\\\"\\\"}"; [ -n "$out" ] && out+=","; out+="\\\"$v\\\""; done; printf \'%s\\n\' "$out" >> "$dest"; }\n'
s=s.replace(needle,insert)
# Build full-verification hash job list while classifying, and carry signature in PLAN.
s=s.replace('echo "[4/5] Classifying titles and collisions..."; : > "$PLAN"; declare -A NAME_COUNTS; SKIPPED=0; CLASSIFIED=0', 'echo "[4/5] Classifying titles and collisions..."; : > "$PLAN"; : > "$WORK.hashjobs"; declare -A NAME_COUNTS; SKIPPED=0; CLASSIFIED=0')
old='NAME_COUNTS["$key"]=$(( ${NAME_COUNTS["$key"]:-0} + 1 )); printf \'%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n\' "$system" "$p" "$file" "$ext" "$stem" "$clean" "$region" "$kind" >> "$PLAN"; CLASSIFIED=$((CLASSIFIED+1));'
new='NAME_COUNTS["$key"]=$(( ${NAME_COUNTS["$key"]:-0} + 1 )); sig=""; if should_hash "$system" "$ext"; then sig="$(file_signature "$p")"; [ "$USE_HASH_CACHE" -eq 0 ] && printf \'%s\\0\' "$p" >> "$WORK.hashjobs"; fi; printf \'%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n\' "$system" "$p" "$file" "$ext" "$stem" "$clean" "$region" "$kind" "$sig" >> "$PLAN"; CLASSIFIED=$((CLASSIFIED+1));'
s=s.replace(old,new)
s=s.replace('if [ "$USE_HASH_CACHE" -eq 0 ]; then : > "$WORK.hashjobs"; : > "$PREHASH_RESULTS"; while IFS=$\'\\t\' read -r psystem pp pfile pext prest; do should_hash "$psystem" "$pext" && printf \'%s\\0\' "$pp" >> "$WORK.hashjobs"; done < "$PLAN"; pv_start=$SECONDS;', 'if [ "$USE_HASH_CACHE" -eq 0 ]; then : > "$PREHASH_RESULTS"; pv_start=$SECONDS;')
s=s.replace('while IFS=$\'\\t\' read -r -u 3 system p file ext stem clean region kind; do', 'while IFS=$\'\\t\' read -r -u 3 system p file ext stem clean region kind sig; do')
s=s.replace('HASH_ELIGIBLE=$((HASH_ELIGIBLE+1)); SYSTEM_ELIGIBLE["$system"]=$(( ${SYSTEM_ELIGIBLE["$system"]:-0} + 1 )); sig="$(file_signature "$p")"; cache_key=', 'HASH_ELIGIBLE=$((HASH_ELIGIBLE+1)); SYSTEM_ELIGIBLE["$system"]=$(( ${SYSTEM_ELIGIBLE["$system"]:-0} + 1 )); cache_key=')
s=s.replace('matched_hkey="$(normalized_dat_hash "$p" "$ext" "$hkey")"', 'file_size="${sig%%|*}"; matched_hkey="$(normalized_dat_hash "$p" "$ext" "$hkey" "$file_size")"')
# Collapse the hottest CSV chains into one-write rows.
repls={
'''      csv_escape "$sha1" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$system" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$p" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$file" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$dat_name" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$dat_rom" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$dat_source" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_system" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_core" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_folder" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_region" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_release" >> "$STAGE_DAT_MATCH"; printf ',' >> "$STAGE_DAT_MATCH"; csv_escape "$meta_license" >> "$STAGE_DAT_MATCH"; printf '\\n' >> "$STAGE_DAT_MATCH"''':'''      csv_row "$STAGE_DAT_MATCH" "$sha1" "$system" "$p" "$file" "$dat_name" "$dat_rom" "$dat_source" "$meta_system" "$meta_core" "$meta_folder" "$meta_region" "$meta_release" "$meta_license"''',
'''      csv_escape "$system" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$p" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$dat_name" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$meta_system" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$meta_core" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$meta_folder" >> "$STAGE_LOCATION_AUDIT"; printf ',' >> "$STAGE_LOCATION_AUDIT"; csv_escape "$loc_status" >> "$STAGE_LOCATION_AUDIT"; printf '\\n' >> "$STAGE_LOCATION_AUDIT"''':'''      csv_row "$STAGE_LOCATION_AUDIT" "$system" "$p" "$dat_name" "$meta_system" "$meta_core" "$meta_folder" "$loc_status"''',
'''csv_escape "$sha1" >> "$STAGE_DAT_UNMATCHED"; printf ',' >> "$STAGE_DAT_UNMATCHED"; csv_escape "$system" >> "$STAGE_DAT_UNMATCHED"; printf ',' >> "$STAGE_DAT_UNMATCHED"; csv_escape "$p" >> "$STAGE_DAT_UNMATCHED"; printf ',' >> "$STAGE_DAT_UNMATCHED"; csv_escape "$file" >> "$STAGE_DAT_UNMATCHED"; printf '\\n' >> "$STAGE_DAT_UNMATCHED"''':'''csv_row "$STAGE_DAT_UNMATCHED" "$sha1" "$system" "$p" "$file"''',
'''csv_escape "$system" >> "$STAGE_SAVE_REN"; printf ',' >> "$STAGE_SAVE_REN"; csv_escape "$p" >> "$STAGE_SAVE_REN"; printf ',' >> "$STAGE_SAVE_REN"; csv_escape "$sp" >> "$STAGE_SAVE_REN"; printf ',' >> "$STAGE_SAVE_REN"; csv_escape "$proposed_save" >> "$STAGE_SAVE_REN"; printf ',' >> "$STAGE_SAVE_REN"; csv_escape "Exact original basename" >> "$STAGE_SAVE_REN"; printf ',' >> "$STAGE_SAVE_REN"; csv_escape "REVIEW ONLY" >> "$STAGE_SAVE_REN"; printf '\\n' >> "$STAGE_SAVE_REN"''':'''csv_row "$STAGE_SAVE_REN" "$system" "$p" "$sp" "$proposed_save" "Exact original basename" "REVIEW ONLY"''',
'''  csv_escape "$system" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$clean" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$region" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$kind" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$file" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$proposed" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$p" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$save_count" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$collision" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$sha1" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$dat_status" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$dat_name" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$dat_rom" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$dat_source" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_system" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_core" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_folder" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_region" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_release" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$meta_license" >> "$STAGE_CSV"; printf ',' >> "$STAGE_CSV"; csv_escape "$loc_status" >> "$STAGE_CSV"; printf '\\n' >> "$STAGE_CSV"''':'''  csv_row "$STAGE_CSV" "$system" "$clean" "$region" "$kind" "$file" "$proposed" "$p" "$save_count" "$collision" "$sha1" "$dat_status" "$dat_name" "$dat_rom" "$dat_source" "$meta_system" "$meta_core" "$meta_folder" "$meta_region" "$meta_release" "$meta_license" "$loc_status"''',
'''  csv_escape "$system" >> "$STAGE_REN"; printf ',' >> "$STAGE_REN"; csv_escape "$p" >> "$STAGE_REN"; printf ',' >> "$STAGE_REN"; csv_escape "$proposed" >> "$STAGE_REN"; printf ',' >> "$STAGE_REN"; csv_escape "$region" >> "$STAGE_REN"; printf ',' >> "$STAGE_REN"; csv_escape "$kind" >> "$STAGE_REN"; printf ',' >> "$STAGE_REN"; csv_escape "REVIEW ONLY" >> "$STAGE_REN"; printf '\\n' >> "$STAGE_REN"''':'''  csv_row "$STAGE_REN" "$system" "$p" "$proposed" "$region" "$kind" "REVIEW ONLY"'''}
for a,b in repls.items():
    if a not in s: raise SystemExit('expected CSV pattern missing')
    s=s.replace(a,b)
if 'sig="$(file_signature "$p")"; cache_key=' in s: raise SystemExit('per-report stat still present')
p.write_text(s)

note='Exporter performance: file signatures are captured once during classification and reused during report/hash-cache processing; Full Verification hash jobs are generated during classification instead of rereading the plan; hot-path CSV output is assembled and written once per row.'
for d in map(Path,['README.md','PROJECT_CONTEXT.md','wiki/Audit-Workflow.md']):
    if d.exists() and note not in d.read_text(): d.write_text(d.read_text().rstrip()+'\n\n'+note+'\n')
