run_update_tools() {
# MiSTer-Audit-Update_v1.4.sh
# Companion updater for MiSTer ROM Library Auditor v1.4

ROOT="/media/fat"; GAMES="$ROOT/games"; SAVES="$ROOT/saves"; AUDIT="$ROOT/GameLibraryAudit"
GAME_CSV="$AUDIT/proposed_renames.csv"; SAVE_CSV="$AUDIT/proposed_save_renames.csv"; CATALOG="$AUDIT/library_catalog.csv"; BUNDLE="$AUDIT/MiSTer_Library_Audit.txt"
HISTORY="$AUDIT/RenameHistory"; PLAN="$AUDIT/apply_preview.tsv"; SKIPS="$AUDIT/apply_skipped.tsv"; PLAN_META="$AUDIT/apply_preview.meta"
SCRIPT_DIR="$(cd "$(dirname "$0")" 2>/dev/null && pwd)"; RUNTIME="$SCRIPT_DIR/MiSTer_Audit.sh"; HASH_DB="$SCRIPT_DIR/mister_hash_database.tsv"
EXPECTED_SCHEMA="4"; EXPECTED_EXPORTER_VERSION="1.4"; BLOCKLIST="/tmp/mister_updater_blocked.$$"; HEARTBEAT_EVERY=500
UPDATER_BUILD="preview-summary-2026-09-13a"
STAGE_PREFIX=""; STAGE_COLLISION=""; STAGE_RESOLVE=""; STAGE_GAME=""; STAGE_SAVE=""
cleanup(){ rm -f "$BLOCKLIST"; }; trap cleanup EXIT INT TERM; mkdir -p "$HISTORY" || exit 1
stage(){ echo; echo "[$1] $2"; }
hash_file(){ local p="$1"; if command -v sha1sum >/dev/null 2>&1; then sha1sum "$p" 2>/dev/null|awk '{print $1}'; elif command -v openssl >/dev/null 2>&1; then openssl sha1 "$p" 2>/dev/null|awk '{print $NF}'; else printf 'UNAVAILABLE'; fi; }
audit_meta(){ local key="$1"; awk -F= -v k="$key" '/^\[AUDIT_METADATA\]$/{inmeta=1;next}/^\[/&&inmeta{exit}inmeta&&$1==k{sub(/^[^=]*=/,"");print;exit}' "$BUNDLE" 2>/dev/null; }
trim_spaces(){ local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; s="${s%"${s##*[![:space:]]}"}"; printf '%s' "$s"; }
validate_audit(){
 local mode="${1:-preview}" schema exporter_version build_sha database_sha metadata_layer self_check verdict recommendation notes notes_trimmed current_exporter_sha current_database_sha errors=0 collision_only=0
 [[ -f "$BUNDLE" ]]||{ echo "ERROR: Missing $BUNDLE"; echo "Run MiSTer_Audit and choose Audit first."; return 1; }
 schema="$(audit_meta schema_version)"; exporter_version="$(audit_meta exporter_version)"; build_sha="$(audit_meta build_sha1)"; database_sha="$(audit_meta database_sha1)"; metadata_layer="$(audit_meta metadata_layer)"; self_check="$(audit_meta self_check)"; verdict="$(audit_meta integrity_verdict)"; recommendation="$(audit_meta apply_recommendation)"; notes="$(audit_meta integrity_notes)"; notes_trimmed="$(trim_spaces "$notes")"
 [[ "$verdict" == "PASS WITH WARNINGS" && "$notes_trimmed" == "collision-review-required" ]]&&collision_only=1
 [[ "$recommendation" == "APPLY WITH SKIPS" && "$notes_trimmed" == *collision* ]]&&collision_only=1
 echo "Audit compatibility check"; echo "-------------------------"; echo "Schema:               ${schema:-MISSING}"; echo "Exporter version:     ${exporter_version:-MISSING}"; echo "Self-check:           ${self_check:-MISSING}"; echo "Metadata layer:       ${metadata_layer:-MISSING}"; echo "Integrity verdict:    ${verdict:-MISSING}"; echo "Apply recommendation: ${recommendation:-MISSING}"; echo "Integrity notes:      ${notes:-MISSING}"
 [[ "$schema" == "$EXPECTED_SCHEMA" ]]||{ echo "ERROR: Expected audit schema $EXPECTED_SCHEMA."; errors=1; }; [[ "$exporter_version" == "$EXPECTED_EXPORTER_VERSION" ]]||{ echo "ERROR: Expected exporter v$EXPECTED_EXPORTER_VERSION."; errors=1; }; [[ "$self_check" == PASS ]]||{ echo "ERROR: Auditor startup self-check did not pass."; errors=1; }; [[ "$metadata_layer" == MiSTer-aware ]]||{ echo "ERROR: MiSTer-aware metadata layer was not validated."; errors=1; }; [[ -n "$build_sha" && "$build_sha" != UNAVAILABLE ]]||{ echo "ERROR: Audit exporter build fingerprint is missing."; errors=1; }; [[ -n "$database_sha" && "$database_sha" != missing && "$database_sha" != UNAVAILABLE ]]||{ echo "ERROR: Audit database fingerprint is missing."; errors=1; }
 if [[ "$mode" == apply ]]; then
  if [[ "$verdict" == FAIL ]]; then echo "ERROR: Apply is blocked by integrity_verdict=FAIL."; errors=1; elif [[ "$verdict" == PASS ]]; then [[ "$recommendation" != "DO NOT APPLY" ]]||{ echo "ERROR: Auditor explicitly recommends DO NOT APPLY."; errors=1; }; elif ((collision_only)); then echo "WARNING: Audit contains collision-only warnings; blocking rows will be skipped automatically."; else echo "ERROR: Apply warnings are not limited to skippable collision rows."; errors=1; fi
  [[ -f "$RUNTIME" ]]||{ echo "ERROR: Current exporter not found."; errors=1; }; if [[ -f "$RUNTIME" ]]; then current_exporter_sha="$(hash_file "$RUNTIME")"; [[ "$current_exporter_sha" == "$build_sha" && "$current_exporter_sha" != UNAVAILABLE ]]||{ echo "ERROR: Exporter changed since this audit. Re-run audit."; errors=1; }; fi
  [[ -f "$HASH_DB" ]]||{ echo "ERROR: Current hash database not found."; errors=1; }; if [[ -f "$HASH_DB" ]]; then current_database_sha="$(hash_file "$HASH_DB")"; [[ "$current_database_sha" == "$database_sha" && "$current_database_sha" != UNAVAILABLE ]]||{ echo "ERROR: Hash database changed since this audit. Re-run audit."; errors=1; }; fi
 else
  if [[ "$verdict" == FAIL ]]; then echo "ERROR: Audit integrity failed."; errors=1; elif ((collision_only)); then echo "WARNING: Collision-only warnings detected; blocking rows will be shown as skipped."; elif [[ "$verdict" == "PASS WITH WARNINGS" || "$recommendation" == "DO NOT APPLY" ]]; then echo "WARNING: Preview allowed, but Apply remains blocked by non-collision warnings."; fi
 fi
 ((errors))&&{ echo "Audit compatibility check: BLOCKED"; return 1; }; echo "Audit compatibility check: PASS"
}
parse_csv(){ local s="$1" c field="" quoted=0 i; CSV_FIELDS=(); for((i=0;i<${#s};i++));do c="${s:i:1}"; if((quoted));then if [[ "$c" == '"' ]];then if [[ "${s:i+1:1}" == '"' ]];then field+='"'; ((i++));else quoted=0;fi;else field+="$c";fi;else case "$c" in '"')quoted=1;; ',')CSV_FIELDS+=("$field");field="";; *)field+="$c";;esac;fi;done; CSV_FIELDS+=("$field"); }
safe_under(){ case "$1" in "$2"/*)return 0;;*)return 1;;esac; }; unsafe_name(){ [[ -z "$1" || "$1" == */* || "$1" == . || "$1" == .. ]]; }
classify_blocking_games(){
 :>"$BLOCKLIST"; [[ -f "$CATALOG" ]]||{ echo "Missing $CATALOG"; return 1; }; local total=0; total=$(( $(wc -l <"$CATALOG")-1)); ((total<0))&&total=0
 stage "$STAGE_COLLISION" "Building collision safety map..."; echo "  Catalog rows: $total"
 awk -v heartbeat="$HEARTBEAT_EVERY" -v total="$total" -v resolve_stage="$STAGE_RESOLVE" '
 function csv_parse(s,a, i,c,n,field,quoted,nextc,k){for(k in a)delete a[k];n=1;field="";quoted=0;for(i=1;i<=length(s);i++){c=substr(s,i,1);if(quoted){if(c=="\""){nextc=substr(s,i+1,1);if(nextc=="\""){field=field "\"";i++}else quoted=0}else field=field c}else{if(c=="\"")quoted=1;else if(c==","){a[n++]=field;field=""}else field=field c}}a[n]=field;return n}
 function trimv(s){sub(/^[[:space:]]+/,"",s);sub(/[[:space:]]+$/,"",s);return s}
 function region_of(stem, s){s=tolower(stem);if(s~/\((usa|us|u)(,|\)|[[:space:]])/||s~/\((ue|u,e|u\+e)\)/)return "USA";if(s~/\((world|w)\)/)return "World";if(s~/\((europe|eur|e)\)/)return "Europe";if(s~/\((japan|jpn|j)\)/)return "Japan";if(s~/\((canada|can)\)/)return "Canada";if(s~/\((australia|aus)\)/)return "Australia";if(s~/\((korea|kor|k)\)/)return "Korea";if(s~/\((brazil|bra|b)\)/)return "Brazil";return "Unknown"}
 function kind_of(stem, s){s=tolower(stem);if(s~/\((proto|prototype|beta|demo|sample)([^a-z]|$)/||s~/\[(proto|prototype|beta|demo|sample)([^a-z]|$)/)return "Prototype/Beta/Demo";if(s~/\((rev|revision)[[:space:]._-]*[0-9a-z]+\)/||s~/\[(rev|revision)[[:space:]._-]*[0-9a-z]+\]/)return "Revision";if(s~/\((unl|unlicensed|homebrew|aftermarket)\)/||s~/\[(unl|unlicensed|homebrew|aftermarket)\]/||s~/ homebrew /||s~/ aftermarket /)return "Homebrew/Unlicensed";if(s~/\[t[^]]*\]/||s~/\(translation/||s~/\(translated/||s~/\(eng\)/||s~/\(english/||s~/translation/||s~/english patched/)return "Translation";if(s~/\[h[^]]*\]/||s~/\(hack/||s~/\(hacked/||s~/\(improvement/||s~/\(redux/||s~/\(randomizer/||s~/ hack /||s~/ improvement /||s~/ randomizer /)return "Hack/Modified";return "Retail/Standard"}
 function clean_title(stem, s,old){s=stem;do{old=s;gsub(/[[:space:]]+\((USA|US|U|World|W|Europe|EUR|E|Japan|JPN|J|Canada|CAN|Australia|AUS|Korea|KOR|Brazil|BRA|UE|U,E|U\+E)\)/,"",s);gsub(/[[:space:]]+\((Rev(ision)?[[:space:]._-]*[0-9A-Za-z]+|Proto(type)?|Beta|Demo|Sample|Unl(icensed)?|Homebrew|Aftermarket|Translation|Translated|Eng(lish)?[^)]*)\)/,"",s);gsub(/[[:space:]]+\[([tThH][^]]*|!|[bBoOfFpPaA][0-9]*|[cCxX])\]/,"",s)}while(s!=old);s=trimv(s);gsub(/[[:space:]][[:space:]]+/," ",s);sub(/[[:space:]]+[-_]$/,"",s);s=trimv(s);if(s=="")s=stem;return s}
 NR==1{next}{nf=csv_parse($0,f);if(nf<21)next;processed++;if(heartbeat>0&&processed%heartbeat==0)print "  Processed " processed " / " total " catalog rows...">"/dev/stderr";sysname=tolower(f[1]);original=f[5];proposed=f[6];rowpath=f[7];collision_status=f[9];dat_status=f[11];ext=original;sub(/^.*\./,"",ext);ext=tolower(ext);stem=original;sub(/\.[^.]*$/,"",stem);region=region_of(stem);kind=kind_of(stem);clean=clean_title(stem);suffix="";if(region!="USA"&&region!="Unknown")suffix=" [" region "]";if(region=="Unknown")suffix=" [Unknown Region]";if(kind!="Retail/Standard")suffix=suffix " [" kind "]";fallback=clean suffix "." ext;g=sysname "|" tolower(fallback);pre=(collision_status!="None"&&collision_status!="");authoritative=(dat_status=="Exact SHA-1"||dat_status=="Normalized SHA-1")?1:0;target=sysname "|" tolower(proposed);r++;paths[r]=rowpath;groups[r]=g;pres[r]=pre;targets[r]=target;final_count[target]++;if(pre){group_rows[g]++;group_auth[g]+=authoritative;gt=g SUBSEP target;group_target_count[gt]++;if(group_target_count[gt]>1)group_duplicate[g]=1}}
 END{print "  Processed " processed " / " total " catalog rows.">"/dev/stderr";print "">"/dev/stderr";print "[" resolve_stage "] Resolving global collision groups...">"/dev/stderr";for(i=1;i<=r;i++){g=groups[i];target=targets[i];pre=pres[i];safe=(!pre)||(group_auth[g]==group_rows[g]&&!group_duplicate[g]);if(final_count[target]>1)print paths[i] "\tblocking collision: duplicate final target";else if(pre&&!safe)print paths[i] "\tblocking collision: unresolved pre-DAT group"}}
 ' "$CATALOG">"$BLOCKLIST"||{ echo "ERROR: Collision safety classification failed."; return 1; }; echo "  Collision safety map complete: $(wc -l <"$BLOCKLIST") blocking rows."
}
build_plan(){
 :>"$PLAN"; :>"$SKIPS"; printf 'type\told_path\tnew_path\n'>"$PLAN"; printf 'type\tpath\treason\n'>"$SKIPS"; declare -A TARGETS BLOCKED_GAMES; local line old proposed new dir ext type block_path block_reason game_path processed=0 total=0
 classify_blocking_games||return 1; while IFS=$'\t' read -r block_path block_reason;do [[ -n "$block_path" ]]&&BLOCKED_GAMES["$block_path"]="$block_reason";done<"$BLOCKLIST"
 [[ -f "$GAME_CSV" ]]||{ echo "Missing $GAME_CSV"; return 1; }; total=$(( $(wc -l <"$GAME_CSV")-1)); ((total<0))&&total=0; stage "$STAGE_GAME" "Building safe game rename plan..."; echo "  Game proposals: $total"
 while IFS= read -r line||[[ -n "$line" ]];do [[ "$line" == '"system"'* ]]&&continue; parse_csv "$line"; processed=$((processed+1)); ((processed%HEARTBEAT_EVERY==0))&&echo "  Processed $processed / $total game proposals..."; old="${CSV_FIELDS[1]}"; proposed="${CSV_FIELDS[2]}"; type=GAME; if [[ -n "${BLOCKED_GAMES["$old"]+x}" ]];then printf '%s\t%s\t%s\n' "$type" "$old" "${BLOCKED_GAMES["$old"]}">>"$SKIPS";continue;fi; safe_under "$old" "$GAMES"||{ printf '%s\t%s\t%s\n' "$type" "$old" "outside games root">>"$SKIPS";continue; }; unsafe_name "$proposed"&&{ printf '%s\t%s\t%s\n' "$type" "$old" "unsafe proposed filename">>"$SKIPS";continue; }; ext="${old##*.}";ext="${ext,,}"; [[ "$ext" == cue ]]&&{ printf '%s\t%s\t%s\n' "$type" "$old" "CUE/BIN set rename disabled">>"$SKIPS";continue; }; [[ -e "$old" ]]||{ printf '%s\t%s\t%s\n' "$type" "$old" "source missing">>"$SKIPS";continue; };dir="${old%/*}";new="$dir/$proposed";[[ "$old" == "$new" ]]&&continue;[[ -e "$new" ]]&&{ printf '%s\t%s\t%s\n' "$type" "$old" "target already exists: $new">>"$SKIPS";continue; };[[ -n "${TARGETS["$new"]+x}" ]]&&{ printf '%s\t%s\t%s\n' "$type" "$old" "duplicate proposed target: $new">>"$SKIPS";continue; };TARGETS["$new"]="$old";printf '%s\t%s\t%s\n' "$type" "$old" "$new">>"$PLAN";done<"$GAME_CSV"; echo "  Processed $processed / $total game proposals."
 stage "$STAGE_SAVE" "Building paired save rename plan..."; if [[ -f "$SAVE_CSV" ]];then total=$(( $(wc -l <"$SAVE_CSV")-1));((total<0))&&total=0;processed=0;echo "  Save proposals: $total";while IFS= read -r line||[[ -n "$line" ]];do [[ "$line" == '"system"'* ]]&&continue;parse_csv "$line";processed=$((processed+1));game_path="${CSV_FIELDS[1]}";old="${CSV_FIELDS[2]}";proposed="${CSV_FIELDS[3]}";type=SAVE;if [[ -n "${BLOCKED_GAMES["$game_path"]+x}" ]];then printf '%s\t%s\t%s\n' "$type" "$old" "game rename skipped: ${BLOCKED_GAMES["$game_path"]}">>"$SKIPS";continue;fi;safe_under "$old" "$SAVES"||{ printf '%s\t%s\t%s\n' "$type" "$old" "outside saves root">>"$SKIPS";continue;};unsafe_name "$proposed"&&{ printf '%s\t%s\t%s\n' "$type" "$old" "unsafe proposed filename">>"$SKIPS";continue;};[[ -e "$old" ]]||{ printf '%s\t%s\t%s\n' "$type" "$old" "source missing">>"$SKIPS";continue;};dir="${old%/*}";new="$dir/$proposed";[[ "$old" == "$new" ]]&&continue;[[ -e "$new" ]]&&{ printf '%s\t%s\t%s\n' "$type" "$old" "target already exists: $new">>"$SKIPS";continue;};[[ -n "${TARGETS["$new"]+x}" ]]&&{ printf '%s\t%s\t%s\n' "$type" "$old" "duplicate proposed target: $new">>"$SKIPS";continue;};TARGETS["$new"]="$old";printf '%s\t%s\t%s\n' "$type" "$old" "$new">>"$PLAN";done<"$SAVE_CSV";echo "  Processed $processed / $total save proposals.";else echo "  No save proposal file found; continuing.";fi
}
plan_counts(){ PLAN_N=$(( $(wc -l <"$PLAN" 2>/dev/null)-1)); SKIP_N=$(( $(wc -l <"$SKIPS" 2>/dev/null)-1)); ((PLAN_N<0))&&PLAN_N=0; ((SKIP_N<0))&&SKIP_N=0; COLLISION_N=$(awk -F'\t' 'NR>1&&$3~/^blocking collision:|^game rename skipped: blocking collision:/{n++}END{print n+0}' "$SKIPS" 2>/dev/null); }
write_plan_meta(){ plan_counts; { echo "generated=$(date '+%Y-%m-%d %I:%M:%S %p %Z')"; echo "audit_mode=$(audit_meta audit_mode)"; echo "safe_renames=$PLAN_N"; echo "skipped_items=$SKIP_N"; echo "collision_blocked=$COLLISION_N"; echo "exporter_build=$(audit_meta build_sha1)"; echo "database_sha1=$(audit_meta database_sha1)"; } > "$PLAN_META"; }
meta_value(){ local key="$1"; awk -F= -v k="$key" '$1==k{sub(/^[^=]*=/,"");print;exit}' "$PLAN_META" 2>/dev/null; }
show_plan_summary(){ plan_counts; echo; echo "Safe rename candidates: $PLAN_N"; echo "Skipped/review items: $SKIP_N"; echo "Collision-blocked rows skipped: $COLLISION_N"; echo "Preview: $PLAN"; echo "Skipped: $SKIPS"; }
view_summary(){
 [[ -f "$PLAN" && -f "$SKIPS" ]]||{ echo "No saved preview summary found. Run Preview safe renames first."; return 1; }; plan_counts; local generated mode; generated="$(meta_value generated)"; mode="$(meta_value audit_mode)"
 echo; echo "Last Preview Summary"; echo "===================="; [[ -n "$generated" ]]&&echo "Generated: $generated"; [[ -n "$mode" ]]&&echo "Audit mode: $mode"; echo; printf 'Safe rename candidates:        %s\n' "$PLAN_N"; printf 'Skipped / review items:        %s\n' "$SKIP_N"; printf 'Collision-blocked rows skipped: %s\n' "$COLLISION_N"; echo; echo "Preview file:"; echo "  $PLAN"; echo; echo "Skipped file:"; echo "  $SKIPS"; echo; echo "Press Enter to return."; read -r _
}
review_preview(){
 [[ -f "$PLAN" ]]||{ echo "No saved preview found. Run Preview safe renames first."; return 1; }; local shown=0 type old new n; n=$(( $(wc -l <"$PLAN")-1)); ((n<0))&&n=0
 echo; echo "Last preview"; echo "============"; echo "Safe rename candidates: $n"; echo
 while IFS=$'\t' read -r type old new; do [[ "$type" == type ]]&&continue; shown=$((shown+1)); ((shown>20))&&break; echo "[$shown] $type"; echo "  From:"; echo "    $old"; echo "  To:"; echo "    $new"; echo; done < "$PLAN"
 ((n>20))&&echo "... $((n-20)) more safe renames are listed in $PLAN"; echo; echo "Press Enter to return."; read -r _
}
review_skips(){
 [[ -f "$SKIPS" ]]||{ echo "No saved skipped-item report found. Run Preview safe renames first."; return 1; }; local shown=0 type path reason n; n=$(( $(wc -l <"$SKIPS")-1)); ((n<0))&&n=0
 echo; echo "Skipped / review items"; echo "======================"; echo "Items: $n"; echo
 while IFS=$'\t' read -r type path reason; do [[ "$type" == type ]]&&continue; shown=$((shown+1)); ((shown>20))&&break; echo "[$shown] $type"; echo "  File:"; echo "    $path"; echo "  Reason:"; echo "    $reason"; echo; done < "$SKIPS"
 ((n>20))&&echo "... $((n-20)) more skipped items are listed in $SKIPS"; echo; echo "Press Enter to return."; read -r _
}
preview(){ STAGE_COLLISION="2/6";STAGE_RESOLVE="3/6";STAGE_GAME="4/6";STAGE_SAVE="5/6";stage "1/6" "Validating audit compatibility...";validate_audit preview||return 1;build_plan||return 1;write_plan_meta;stage "6/6" "Finalizing preview...";show_plan_summary;echo;echo "Preview complete.";echo "Press Enter to review the last preview, or Ctrl+C to close.";read -r _;review_preview; }
apply_plan(){ STAGE_COLLISION="2/8";STAGE_RESOLVE="3/8";STAGE_GAME="4/8";STAGE_SAVE="5/8";stage "1/8" "Validating audit compatibility...";validate_audit apply||return 1;build_plan||return 1;write_plan_meta;stage "6/8" "Reviewing safe rename plan...";local n stamp manifest type old new;n=$(( $(wc -l <"$PLAN")-1));((n>0))||{ echo "Nothing safe to rename.";return 0;};show_plan_summary;echo;echo "This will rename $n safe files. Collision-blocked rows and their saves remain untouched.";echo "Type APPLY exactly to continue:";read -r confirm;[[ "$confirm" == APPLY ]]||{ echo "Cancelled.";return 0;};stage "7/8" "Revalidating and rebuilding safe plan...";validate_audit apply||return 1;STAGE_COLLISION="7a/8";STAGE_RESOLVE="7b/8";STAGE_GAME="7c/8";STAGE_SAVE="7d/8";build_plan||return 1;write_plan_meta;stage "8/8" "Applying safe renames and writing rollback manifest...";stamp=$(date +%Y%m%d-%H%M%S);manifest="$HISTORY/rename-$stamp.tsv";printf 'type\told_path\tnew_path\tresult\n'>"$manifest";tail -n +2 "$PLAN"|while IFS=$'\t' read -r type old new;do if [[ -e "$old" && ! -e "$new" ]];then if mv -- "$old" "$new";then printf '%s\t%s\t%s\tOK\n' "$type" "$old" "$new">>"$manifest";else printf '%s\t%s\t%s\tFAILED\n' "$type" "$old" "$new">>"$manifest";fi;else printf '%s\t%s\t%s\tSKIPPED_AT_APPLY\n' "$type" "$old" "$new">>"$manifest";fi;done;cp "$manifest" "$HISTORY/last_manifest.tsv";echo "Finished. Rollback manifest: $manifest"; }
rollback(){ local manifest="$HISTORY/last_manifest.tsv" type old new result;[[ -f "$manifest" ]]||{ echo "No last rollback manifest found.";return 1;};echo "Rollback will restore successful renames from:";echo "$manifest";echo "Type ROLLBACK exactly to continue:";read -r confirm;[[ "$confirm" == ROLLBACK ]]||{ echo "Cancelled.";return 0;};tail -n +2 "$manifest"|tac|while IFS=$'\t' read -r type old new result;do [[ "$result" == OK ]]||continue;if [[ -e "$new" && ! -e "$old" ]];then mv -- "$new" "$old"||echo "FAILED: $new";else echo "SKIP: cannot safely restore $old";fi;done;echo "Rollback pass finished. Re-run the auditor to verify the library."; }
echo "MiSTer ROM Library Updater v1.4";echo "=================================";echo "Updater build: $UPDATER_BUILD";echo "Script path:   $0";echo "1) Preview safe renames";echo "2) Apply safe renames (blocking collisions auto-skipped)";echo "3) View last preview summary";echo "4) Review last preview";echo "5) Review skipped items";echo "6) Roll back last applied cleanup";echo "7) Exit";IFS= read -rsn1 choice;echo;case "$choice" in 1)preview;;2)apply_plan;;3)view_summary;;4)review_preview;;5)review_skips;;6)rollback;;*)exit 0;;esac

}
